version: '3.7'

services:

  app:
    container_name: app
    image: braceyourself/akaunting
    build:
      context: ./
    volumes:
      - ./.env:/var/www/html/.env
      - app:/var/www/html
      - ./storage:/var/www/html/storage
    restart: unless-stopped
    environment:
      - AKAUNTING_SETUP
    depends_on:
      - mysql

  web:
    image: nginx
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.akaunting.rule=Host(`${APP_DOMAIN}`)"
      - "traefik.backend=${APP_DOMAIN}"
      - "traefik.frontend.rule=Host:${APP_DOMAIN}"
      - "traefik.docker.network=traefik"
    environment:
      SERVICE_NAME: app
      SERVICE_PORT: 9000
    volumes:
      - ./nginx:/etc/nginx/templates
      - app:/var/www/html
    networks:
      - traefik
      - default
    depends_on:
      - app


  mysql:
    image: mysql
    environment:
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    volumes:
      - ./mysql/data:/var/lib/mysql
    restart: unless-stopped

  akaunting-update:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup app


networks:
  traefik:
    external: true

volumes:
  app:
